### ISSUE TITLE
Unimplimented Design Features

### ISSUE THREAD

**Issue by clandry94** [Almost-There/almostThere#7]
Pulse user's chosen color on thier username when viewed as plantext
Use user's preferred color to put behind their avatars for semi transparent accented avatars are possible

Collect sound files, figure out how to JS them to hovering on shit by applying classes, add that to toggle menu
(Drippy noises, (steam big picture, touchwiz android 4.0+, WP8 Lumia lock screen sound)

Slide in from right, each settings menu block when settings menu is opened.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
As a main point for everyone(!) I propose to try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
